using Generated;
using Microsoft.AspNetCore.Mvc.Testing;
using System.Threading.Tasks;
using Xunit;

namespace ActiveCaching.Tests
{
    /// <summary>
    /// This code was generated by a tool.
    /// Generation Time: 00:00:00.0005530
    /// Generation Date: 2020-06-10 12:48:51 AM +00:00
    /// </summary>
    public class OrderControllerTests : IClassFixture<WebApplicationFactory<Startup>>
    {
        private readonly WebApplicationFactory<Startup> _factory;

        public OrderControllerTests(WebApplicationFactory<Startup> factory)
        {
            _factory = factory;
        }

        [Theory]
        [InlineData("/order")]
        public async Task Get(string url)
        {
            var client = _factory.CreateClient();
            var response = await client.GetAsync(url);
            response.EnsureSuccessStatusCode();
        }
    }
}
